# Compose Development Edition
name: stock-video-metadata-dev

services:
  enrich-api:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    image: enrichment-api:dev
    container_name: enrich-api-dev
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./app:/workspace/app
      - ./scripts:/workspace/scripts
      - ./metadata:/workspace/metadata
      - ./data:/workspace/data
      - B:/:workspace/smb
    ports:
      - "18000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 18000 --reload
    runtime: nvidia
    platform: linux/amd64
    labels:
      com.cdaprod.project: "Blackbox Video Enrichment API"
      com.cdaprod.version: "0.1.0-dev"
      com.cdaprod.env: "development"
      com.cdaprod.description: "FastAPI service for AI-powered video metadata enrichment"
      com.cdaprod.maintainer: "Cdaprod <cdaprod@cdaprod.dev>"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

x-project:
  author: "cdaprod.dev"
  description: "Dev compose for single FastAPI enrichment API"
  stack: "FastAPI + Uvicorn + CUDA11.8"
  services: [enrich-api]
  volumes: ["./app", "./scripts", "./metadata", "./data"]